### ISSUE TITLE
Error while creating profile in trace

### ISSUE THREAD

**Issue by nikhidas26** [kairos-tech-com/Trace-H.R#1]
When trying to create a profile I am running through the following errors

Attached is the screenshot

![screen shot 2018-05-27 at 3 34 10 pm](https://user-images.githubusercontent.com/8550144/40584730-8c679ef4-61c3-11e8-9bec-dee03b06b53c.jpg)

**Comment by nikhidas26** [comment]
Well this is intermittent, I am currently running into this 


![screen shot 2018-05-27 at 6 14 05 pm](https://user-images.githubusercontent.com/8550144/40586080-c7a06e7c-61d9-11e8-8750-1b9729cf0d48.jpg)

**Comment by Akashjanani** [comment]
The error was occuring due to the req.body being undefined from the client. Fixed it. Closing the issue.
