### ISSUE TITLE
Confirmation mail is not working

### ISSUE THREAD

**Issue by Sirisha-Muddana** [kairos-tech-com/Trace-H.R#10]
Hello Sir, 
      Signed up successfully, getting the confirmation mail to which I have registered, but that confirmation mail link is not working. It is  showing "404error page"

![screenshot 180](https://user-images.githubusercontent.com/37927730/41142294-c9343092-6b12-11e8-9887-4a6c07e2af25.png)
![confirmation](https://user-images.githubusercontent.com/37927730/41142446-59b453cc-6b13-11e8-85e9-09d1db812c82.PNG)
![screenshot 181](https://user-images.githubusercontent.com/37927730/41142527-a30daeba-6b13-11e8-8ae2-a0123120e125.png)

**Comment by Akashjanani** [comment]
Fixed. Please check now.
