### ISSUE TITLE
Forget password is not working as expected

### ISSUE THREAD

**Issue by nikhidas26** [kairos-tech-com/Trace-H.R#2]
Here are the steps to create the issue

1) Sign up with my email id
2) Successfully signed up and routed to login page
3) Click on forget password
4) It takes me to the forget password page, however when I enter my email id it says , " Please check your email again"

The expectation was to -> Get the reset link to the email id. 

Attached are the screenshots

![screen shot 2018-06-05 at 11 44 48 am](https://user-images.githubusercontent.com/8550144/40958352-a2876ae4-68b6-11e8-96cf-4df874d1acda.jpg)

![screen shot 2018-06-05 at 11 44 54 am](https://user-images.githubusercontent.com/8550144/40958351-a2607330-68b6-11e8-8dbf-834a079b9470.jpg)

![screen shot 2018-06-05 at 11 51 30 am](https://user-images.githubusercontent.com/8550144/40958411-cea755bc-68b6-11e8-9810-3c94b356f132.jpg)

**Comment by Akashjanani** [comment]
Issue addressed. Right now I have setup a dummy email account at mailtrap.io. I have to change the smtp settings in nodemailer to send emails via a kairostech domain id that we will have to create. I can give you access to the mailtrap.io account to check functionality. It works as expected.

**Comment by Akashjanani** [comment]
![image](https://user-images.githubusercontent.com/20525711/40978184-904d0e56-6898-11e8-9d00-2cd8f9b22ad9.png)

Attached screenshot for verification that the email account has received all the emails.
Clicking on the link takes you back to trace which lets you create a new password.

**Comment by Sirisha-Muddana** [comment]
Okay. Give me the access, I will grow through it.

**Comment by Akashjanani** [comment]
Sorry, it's actually connected to my github account. They're creating a new email for kairos and then you should be able to receive emails to your own account.

**Comment by Akashjanani** [comment]
This has been fixed. Should work now.
