### ISSUE TITLE
Signup confirmation mail is not working as expected

### ISSUE THREAD

**Issue by Sirisha-Muddana** [kairos-tech-com/Trace-H.R#3]
1. Sign up with my email id.
2. Successfully signed up.
3. Before sign in, we need to get a confirmation email to my mail. But, I did not get that confirmation to my email id.
4. Without that confirmation email, we are getting a  access to login.

The expectation was to-->Get the confirmation email before you log in.

**Comment by Akashjanani** [comment]
That actually makes sense. The user shouldn't be able to access without verification. The logic that I currently have lets the user sign in but keeps nagging them with a message to verify their email. Also, once I get the kairostech email I will update the changes and then it should work.

**Comment by Akashjanani** [comment]
This has been fixed. An AWS bug is now causing it to show a 404 error when clicking on the confirmation link.  For reference: https://keita.blog/2015/11/24/hosting-a-single-page-app-on-s3-with-proper-urls/
