### ISSUE TITLE
Edit profile is not working

### ISSUE THREAD

**Issue by jvatarun** [kairos-tech-com/Trace-H.R#4]
Hello,

1. Logged in successfully
2. After creating the profile by clicking on "create profile " 
3. If I want to edit the profile by clicking on "Edit profile". 
4. Getting 404 Not found Error

Expectation - view the details of the profile while creating and have an. option of EDIT

Screen shot attached 

![screen shot 2018-06-06 at 11 23 01 am](https://user-images.githubusercontent.com/37924894/41019394-0818fb14-697c-11e8-9ab0-7ab8378ec780.png)

**Comment by Akashjanani** [comment]
Edit profile should work as expected. The 404 error you're seeing is because of an AWS bug. I have referenced this error in slack. Here's the link again for reference: 
https://keita.blog/2015/11/24/hosting-a-single-page-app-on-s3-with-proper-urls/
