### ISSUE TITLE
Increment and decrement arrows are not necessary 

### ISSUE THREAD

**Issue by jvatarun** [kairos-tech-com/Trace-H.R#8]
Hello, 

1.When I tried to create a profile in the details section 
2. For the Zip code and contact number, the Increment and decrement arrows were not required

Attached Screenshot - 

![screen shot 2018-06-06 at 4 08 58 pm](https://user-images.githubusercontent.com/37924894/41033408-10569d4a-69a4-11e8-9c0e-78e5392f36a6.png)

**Comment by Akashjanani** [comment]
Going to add validations to it. Thank you.

**Comment by Akashjanani** [comment]
Fixed. Please re-test
